meta_product_name: "Les Sentiers Pédagogiques de Cantaron"
meta_title: "Les Sentiers Pédagogiques de Cantaron"
meta_description: "Partez à la découverte de la nature
                et de la culture du Mont Macaron avec
                les Sentiers Pédagogiques de Cantaron"
meta_image: "logo.png"
